[package]
name = "regginator/luaencode"
description = "Optimal Table Serialization for Native Luau/Lua 5.1+"
version = "1.2.3"
license = "MIT"
authors = ["Reggie <reggie@latte.to>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["**"]
include = ["LICENSE.txt", "src", "src/*", "default.project.json", "wally.toml", "wally.lock", "version.txt"]

[dependencies]
