[package]
name = "regginator/luaencode"
description = "Fast Table Serialization Library for Pure Luau/Lua 5.1+"
version = "1.4.2"
license = "MIT"
authors = ["reggie <reggie@latte.to>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["**"]
include = ["LICENSE", "src", "src**", "default.project.json", "wally.toml"]

[dependencies]
