[package]
name = "regginator/luaencode"
description = "Utility Module for Optimal Serialization of Lua Tables in Luau/Lua 5.1+ "
version = "0.3.0"
license = "MIT"
authors = ["Reggie <reggie@latte.to>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = ["src", "default.project.json", "LICENSE.txt"]

[dependencies]
