[package]
name = "regginator/luaencode"
description = "Optimal Serialization of Lua Tables in Native Luau/Lua 5.1+"
version = "1.1.1"
license = "MIT"
authors = ["Reggie <reggie@latte.to>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = ["src", "default.project.json", "LICENSE.txt"]

[dependencies]
